### ISSUE TITLE
Put a geocoder service on the architecture scheme

### ISSUE THREAD

**Issue by oleksmarkh** [Crisismap/crisismap-links#1]
As discussed with @zverev and @Godnik, a call to third-party service should be executed to enrich retrieved data with normalised location metadata.

Two alternatives:
1. Each **provider** is responsible for calling the **geocoder** and compiling it's response together *before* saving into DB. Since such operation is common enough, could be up to **generic provider** pattern.
2. Geocoding is happening inside **back-end**. That way, to avoid additional queuing/marking, geocoding should also happen *before* data got insetred into DB, meaning dedicated `POST` API should take place - exclusively for **providers** to supplie.

See:
* https://developers.google.com/maps/documentation/geocoding/intro
* http://wiki.openstreetmap.org/wiki/Nominatim

**Comment by Godnik** [comment]
I only know that *after* the information about toponym is extracted )

**Comment by oleksmarkh** [comment]
scheme is updated, the 1st approach is used for now
